### ISSUE TITLE
Add switch to hide up-to-date exercises

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/tracks-maintenance-dashboard#16]
https://github.com/exercism/exercism/issues/5056

**Comment by SleeplessByte** [comment]
@trblackw respond here, otherwise I can't assign you 💯

**Comment by trblackw** [comment]
Hey @SleeplessByte id like to take this on if you want to assign me 🤘🏼

**Comment by trblackw** [comment]
@SleeplessByte Can you provide some clarity as to how the styling paradigm is currently set up in this repo? I'm assuming the styles are being derived from another repo because there's a singular css file that is pretty bare. 
The xbytes repo you pointed me to seems to be using emotion, which is not a current project dep. I already have a toggler/switch that is identical to the one in xbytes but before I move forward with bringing it in to the project I want to make sure I conform to the styling paradigm and get your go-ahead before adding any dependencies. My toggler is built with styled-components but I can port it over to whatever.

**Comment by SleeplessByte** [comment]
It's just using bootstrap, some inline styles and that super bare CSS file 😁😁.

Do whatever you feel like. I'm pretty comfortable with css, css in js, and everything in between.

**Comment by trblackw** [comment]
What should the verbiage be here? In other words, what would the label be for the switch component

**Comment by SleeplessByte** [comment]
Also, I tried to find you on discord but it errors! 

[Here](https://join.slack.com/t/exercism-team/shared_invite/enQtNDEyMDM0OTgzNzY1LTU2ZDE2MGIzZmJmMDY3MDc1M2MxMzA0YjkwNjYyY2E1ZWJmNDRjNjVhMzc4OGQzOTU3Y2JkMTQ3ZTA5MWI3OGU) is the join us on slack link.

**Comment by trblackw** [comment]
Joined and posted an intro!
